language: c

install: true

branches:
  only:
  - master

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: make -C hello/ clean all
    - before_script:
        - make -C hello/ clean all
    - stage: test
      script: hello/hello
