language: c

install: true

branches:
  only:
  - master

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script: make -C lab6/hello clean all
    - stage: test
      script: lab6/hello/hello
